name: ⭐ Feature request
description: Create a detailed request for a new feature.
title: 'feat: '
labels: ['Feature request']
body:
  - type: markdown
    attributes:
      value: |
        # Morphe (Manager) feature request

        Before creating a new feature request, please keep the following in mind:

        - **Do not submit a duplicate feature request**: Search for existing feature requests [here](https://github.com/MorpheApp/morphe-manager/issues?q=is%3Aissue).
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe your feature in detail
        - Add images, videos, links, examples, references, etc. if possible
  - type: textarea
    attributes:
      label: Motivation
      description: |
        A strong motivation is necessary for a feature request to be considered.

        - Why should this feature be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this feature important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your feature request will be closed if you don't follow the checklist below.
      options:
        - label:  I have checked all open and closed feature requests and this is not a duplicate.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: The feature request is only related to Morphe (Manager).
          required: true